FROM eu.gcr.io/gitpod-core-dev/dev/dev-environment:aledbf-leeway-pigz-gha.18593@sha256:43c81bc74cda8e874ab8301bd2153861d5c81e7b9ce6905e2303adc919acd378

COPY entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
