on:
  pull_request:
    paths:
      - components/spicedb/**
      - .github/workflows/authorization.yml

name: SpiceDB

jobs:
  scan-repo:
    runs-on: ubuntu-latest
    name: Validate schema
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@1b05615854632b887b69ae1be8cbefe72d3ae423 # v2.6.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Validate SpiceDB schema
        uses: authzed/action-spicedb-validate@3c2214196c200ff012a12d4fc12204efa7a3a416 # v1.0.1
        with:
          validationfile: "components/spicedb/schema/schema.yaml"
