name: Code Nightly

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  create-runner:
    uses: gitpod-io/gce-github-runner/.github/workflows/create-vm.yml@main
    secrets:
      runner_token: ${{ secrets.SELF_HOSTED_GITHUB_RUNNER_TOKEN }}
      gcp_credentials: ${{ secrets.SELF_HOSTED_GITHUB_RUNNER_GCP_CREDENTIALS }}

  build:
    runs-on: ${{ needs.create-runner.outputs.label }}
    needs: [create-runner]
    container:
      image: eu.gcr.io/gitpod-core-dev/dev/dev-environment:aledbf-leeway-pigz-gha.18593
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@1b05615854632b887b69ae1be8cbefe72d3ae423 # v2.6.0
        with:
          egress-policy: audit

      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: ./.github/actions/setup-environment
        with:
          sa_key: ${{ secrets.GCP_CREDENTIALS }}
          leeway_segment_key: ${{ secrets.LEEWAY_SEGMENT_KEY }}
      - id: build-code
        name: Build
        env:
          PR_DESC: "${{ steps.pr-details.outputs.pr_body }}"
          MAIN_BRANCH: ${{ (github.head_ref || github.ref) == 'refs/heads/main' }}
        run: |
          export LEEWAY_WORKSPACE_ROOT=$GITHUB_WORKSPACE

          codeHeadCommit=$(curl -H 'Accept: application/vnd.github.VERSION.sha' https://api.github.com/repos/gitpod-io/openvscode-server/commits/gp-code/main)
          codeVersion=$(curl https://raw.githubusercontent.com/gitpod-io/openvscode-server/$codeHeadCommit/package.json | jq .version)
          cd components/ide/code
          leeway build \
            -Dversion=nightly \
            -DimageRepoBase=eu.gcr.io/gitpod-core-dev/build \
            -DcodeCommit=$codeHeadCommit \
            -DcodeVersion=$codeVersion \
            -DcodeQuality=insider \
            .:docker
      - name: Get previous job's status
        id: lastrun
        uses: filiptronicek/get-last-job-status@1c211ff20d1706ff0bc3fc8022f7bd6518b88bc4 # main
      - name: Slack Notification
        if: ${{ (success() && steps.lastrun.outputs.status == 'failed') || failure() }}
        uses: rtCamp/action-slack-notify@12e36fc18b0689399306c2e0b3e0f2978b7f1ee7 # v2.2.0
        env:
          SLACK_WEBHOOK: ${{ secrets.IDE_SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_FOOTER: "<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|Workflow logs>"

  delete-runner:
    if: always()
    needs:
      - create-runner
      - build
    uses: gitpod-io/gce-github-runner/.github/workflows/delete-vm.yml@main
    secrets:
      gcp_credentials: ${{ secrets.SELF_HOSTED_GITHUB_RUNNER_GCP_CREDENTIALS }}
    with:
      runner-label: ${{ needs.create-runner.outputs.label }}
      machine-zone: ${{ needs.create-runner.outputs.machine-zone }}
