on:
  push:
    branches:
      - main
name: Configcat code references
jobs:
  scan-repo:
    runs-on: ubuntu-latest
    name: Scan repository for configcat code references
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@1b05615854632b887b69ae1be8cbefe72d3ae423 # v2.6.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Scan & upload
        uses: configcat/scan-repository@17c5a8ad884082b4fb021bff83077ef1978b17a0 # v1.1.0
        with:
          api-user: ${{ secrets.CONFIGCAT_API_USER }}
          api-pass: ${{ secrets.CONFIGCAT_API_PASS }}
          config-id: 08da1258-6541-4fc7-8b61-c8b47f82f3a0
