on:
  workflow_call:
    inputs:
      productId:
        type: string
        required: true
      productCode:
        type: string
        required: true
    secrets:
      projectId:
        required: true
      serviceAccountKey:
        required: true
      slackWebhook:
        required: true

jobs:
  update-jetbrains:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@1b05615854632b887b69ae1be8cbefe72d3ae423 # v2.6.0
        with:
          egress-policy: audit

      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      - uses: actions/setup-go@bfdd3570ce990073878bf10f6b2d79082de49492 # v2.2.0
        with:
          go-version: "1.19"
      - name: Download leeway
        run: cd /usr/local/bin && curl -fsSL https://github.com/gitpod-io/leeway/releases/download/v0.7.3/leeway_0.7.3_Linux_x86_64.tar.gz | tar xz
      - name: Download golangci-lint
        run: cd /usr/local && curl -fsSL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.49.0
      - name: Download GoKart
        run: cd /usr/local/bin && curl -L https://github.com/praetorian-inc/gokart/releases/download/v0.4.0/gokart_0.4.0_linux_x86_64.tar.gz | tar xzv gokart
      - name: Auth Google Cloud SDK
        uses: google-github-actions/auth@c4799db9111fba4461e9f9da8732e5057b394f72 # v0.8.3
        with:
          credentials_json: ${{ secrets.serviceAccountKey }}
      - uses: actions/setup-java@91d3aa4956ec4a53e477c4907347b5e3481be8c9 # v2.5.1
        with:
          distribution: zulu
          java-version: "11"
      - name: Setup Google Cloud
        uses: google-github-actions/setup-gcloud@ee9693ff89cdf73862b8a13988f6a71070e8fc58 # v0.6.2
        with:
          project_id: ${{ secrets.projectId }}
      - name: Find IDE version to download
        id: ide-version
        run: |
          IDE_VERSIONS_JSON=$(bash ./components/ide/jetbrains/image/resolve-latest-ide-version.sh ${{ inputs.productCode }})
          IDE_BUILD_VERSION=$(echo "$IDE_VERSIONS_JSON" | jq -r .IDE_BUILD_VERSION)
          IDE_VERSION=$(echo "$IDE_VERSIONS_JSON" | jq -r .IDE_VERSION)
          echo "IDE_BUILD_VERSION: $IDE_BUILD_VERSION"
          echo "IDE_VERSION: $IDE_VERSION"
          echo "::set-output name=ideBuildVersion::$IDE_BUILD_VERSION"
          echo "::set-output name=ideVersion::$IDE_VERSION"
      - name: Leeway build
        if: ${{ steps.ide-version.outputs.ideBuildVersion }}
        env:
          LEEWAY_MAX_PROVENANCE_BUNDLE_SIZE: "8388608"
          LEEWAY_REMOTE_CACHE_BUCKET: '${{ needs.configuration.outputs.leeway_cache_bucket }}'
        run: |
          gcloud auth configure-docker --quiet
          export LEEWAY_WORKSPACE_ROOT=$(pwd)
          cd components/ide/jetbrains/image
          leeway build -Dversion=latest -DimageRepoBase=eu.gcr.io/gitpod-core-dev/build -DbuildNumber=${{ steps.ide-version.outputs.ideBuildVersion }} .:${{ inputs.productId }}-latest -DjbBackendVersion=${{ steps.ide-version.outputs.ideVersion }}
      - name: Get previous job's status
        id: lastrun
        uses: filiptronicek/get-last-job-status@1c211ff20d1706ff0bc3fc8022f7bd6518b88bc4 # main
      - name: Slack Notification
        if: ${{ (success() && steps.lastrun.outputs.status == 'failed') || failure() }}
        uses: rtCamp/action-slack-notify@12e36fc18b0689399306c2e0b3e0f2978b7f1ee7 # v2.2.0
        env:
          SLACK_WEBHOOK: ${{ secrets.slackWebhook }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_TITLE: ${{ inputs.productId }}
          SLACK_FOOTER: "<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|Workflow logs>"
