name: "Preview environment delete"
on:
  workflow_dispatch:
    inputs:
      name:
        required: true
        description: "The name of the preview environment to delete"
  delete:

jobs:
  create-runner:
    uses: gitpod-io/gce-github-runner/.github/workflows/create-vm.yml@main
    secrets:
      runner_token: ${{ secrets.SELF_HOSTED_GITHUB_RUNNER_TOKEN }}
      gcp_credentials: ${{ secrets.SELF_HOSTED_GITHUB_RUNNER_GCP_CREDENTIALS }}

  delete:
    if: github.event.ref_type == 'branch' || github.event.inputs.name != ''
    runs-on: ${{ needs.create-runner.outputs.label }}
    needs: [create-runner]
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@1b05615854632b887b69ae1be8cbefe72d3ae423 # v2.6.0
        with:
          egress-policy: audit

      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Delete preview environment
        uses: ./.github/actions/delete-preview
        with:
          name: ${{ github.event.inputs.name || github.event.ref}}
          sa_key: ${{ secrets.GCP_CREDENTIALS }}

  delete-runner:
    if: always()
    needs:
      - create-runner
      - delete
    uses: gitpod-io/gce-github-runner/.github/workflows/delete-vm.yml@main
    secrets:
      gcp_credentials: ${{ secrets.SELF_HOSTED_GITHUB_RUNNER_GCP_CREDENTIALS }}
    with:
      runner-label: ${{ needs.create-runner.outputs.label }}
      machine-zone: ${{ needs.create-runner.outputs.machine-zone }}
